apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: redis
    protocol: TCP
    name: redis
  - port: 16379
    targetPort: cluster
    protocol: TCP
    name: cluster
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.service.port }}
    targetPort: redis
    protocol: TCP
    name: redis
  - port: 16379
    targetPort: cluster
    protocol: TCP
    name: cluster
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.port }}
    targetPort: redis
    protocol: TCP
    name: redis
    nodePort: 30379
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
{{- end }}
